# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  server_integration_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '14.18.3'
          cache: 'yarn'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.4'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Integration Tests
        run: yarn test
        env:
          CI: true
